Service : User - findByLogin() added, Authentication logic implemente…
DariaPikul/OnlineShop pull request #7
Opened 2020-09-14 14:12 UTC by DariaPikul

2020-09-14 14:22 UTC, andriylagun approved these changes
well done!

2020-09-15 08:36 UTC, KseniiaMakarova requested changes

2020-09-15 08:36 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controller/AuthenticationController.java
> +public class AuthenticationController extends HttpServlet {
```suggestion
public class LoginController extends HttpServlet {
```

2020-09-15 08:36 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controller/AuthenticationController.java
> +            session.setAttribute("user_id", user.getId());
let's make `user_id` a constant

2020-09-15 08:36 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/security/AuthenticationServiceImpl.java
> +        if (existingUser.getPassword().equals(password)) {
let's check all conditions inside `if` so that we could throw our Exception only once

2020-09-15 08:36 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/views/authentication.jsp
> +    <title>Top Store | Authorization</title>
```suggestion
    <title>Top Store | Login</title>
```

2020-09-15 08:36 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/views/welcome.jsp
> +                    secret weapon
nice :)

2020-09-15 08:36 UTC, KseniiaMakarova commented on src/main/webapp/web.xml
> +        <url-pattern>/authentication</url-pattern>
```suggestion
        <url-pattern>/login</url-pattern>
```

2020-09-15 10:29 UTC, KseniiaMakarova approved these changes

2020-09-15 11:09 UTC, merged